version: "3.2"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: testtest
    volumes:
      - ./tmp/.docker_data/postgres:/var/lib/postgresql/data/
    profiles:
      - "psql"

  api:
    build:
      context: .
    image: api:latest
    container_name: api
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - postgres

    profiles:
      - "app"

